GET http://localhost:8080/
###

GET http://localhost:8080/users
###

POST http://localhost:8080/users
Content-Type: application/json

{
    "id": "4",
    "name": "test no.4",
    "description": "Ace"
}
###

DELETE http://localhost:8080/users/2
###


GET http://localhost:8080/movies
###

POST http://localhost:8080/movies
Content-Type: application/json

{
   "id" : "5",
   "title" : "Micheal  Boy",
   " director" : "Tansformers dark of the mood",
}
###

GET http://localhost:8080/movies/1
###